name: coref
channels:
- pytorch
- defaults
dependencies:
- cuda90
- cudnn
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pip
- python
- pytorch
- tqdm
- pandas
- scikit-learn
- spacy
- pip:
  - pytorch-pretrained-bert
  - GitPython
  - tensorflow-gpu
  - tensorboardX
  - allennlp
  - jsonlines