name: coref
channels:
- pytorch
- defaults
dependencies:
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pip
- python
- pytorch
- tqdm
- pandas
- scikit-learn
- pip:
  - pytorch-pretrained-bert
  - GitPython
  - tensorflow
  - tensorboardX
  - allennlp
  - jsonlines